insert into tb_clientes (id, nome) values (1, 'BANCO DA COREIA DO NORTE');
insert into tb_clientes (id, nome) values (2, 'HIPERMERCADOS DEFENDEVA');
insert into tb_clientes (id, nome) values (3, 'BUGUINHO SYSTEMS');


insert into tb_processos (id, numero_do_processo, cliente) values (1, '5643', 2);
insert into tb_processos (id, numero_do_processo, cliente) values (2, '4451', 2);
insert into tb_processos (id, numero_do_processo, cliente) values (3, '3492', 2);
insert into tb_processos (id, numero_do_processo, cliente) values (4, '2721', 2);
insert into tb_processos (id, numero_do_processo, cliente) values (5, '8697', 1);
insert into tb_processos (id, numero_do_processo, cliente) values (6, '1742', 1);
insert into tb_processos (id, numero_do_processo, cliente) values (7, '7854', 1);
insert into tb_processos (id, numero_do_processo, cliente) values (8, '1649', 3);
insert into tb_processos (id, numero_do_processo, cliente) values (9, '4990', 1);
insert into tb_processos (id, numero_do_processo, cliente) values (10, '3962', 3);
insert into tb_processos (id, numero_do_processo, cliente) values (11, '3725', 1);
insert into tb_processos (id, numero_do_processo, cliente) values (12, '3495', 2);
insert into tb_processos (id, numero_do_processo, cliente) values (13, '1200', 3);
insert into tb_processos (id, numero_do_processo, cliente) values (14, '1786', 2);
insert into tb_processos (id, numero_do_processo, cliente) values (15, '7648', 3);

insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (1, 'intimacao', '3495', '2023-04-06', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (2, 'intimacao', '1742', '2023-04-13', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (3, 'publicacao', '4990', '2023-04-09', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (4, 'intimacao', '1786', '2023-04-14', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (5, 'publicacao', '1742', '2023-04-10', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (6, 'intimacao', '7648', '2023-04-09', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (7, 'intimacao', '4451', '2023-04-14', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (8, 'publicacao', '1200', '2023-04-14', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (9, 'intimacao', '8697', '2023-04-11', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (10, 'publicacao', '3725', '2023-04-12', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (11, 'publicacao', '7854', '2023-04-08', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (12, 'intimacao', '7648', '2023-04-10', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (13, 'intimacao', '1742', '2023-04-14', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (14, 'publicacao', '1786', '2023-04-10', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (15, 'intimacao', '3725', '2023-04-08', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (16, 'intimacao', '7854', '2023-04-08', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (17, 'publicacao', '7648', '2023-04-08', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (18, 'intimacao', '1786', '2023-04-14', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (19, 'publicacao', '1786', '2023-04-10', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (20, 'intimacao', '1786', '2023-04-10', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (21, 'publicacao', '8697', '2023-04-09', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (22, 'intimacao', '4990', '2023-04-12', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (23, 'intimacao', '1742', '2023-04-12', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (24, 'publicacao', '5643', '2023-04-14', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.');
insert into tb_intimacoes_e_publicacoes (id, tipo, processo, data, texto) values (25, 'intimacao', '2721', '2023-04-09', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');